// SPDX-FileCopyrightText: 2026 Swift Raccoon
// SPDX-License-Identifier: GPL-2.0-or-later OR GPL-3.0-or-later

import Foundation

/// Conservative correspondence between the stable MCP-D75 setting IDs and
/// the menu numbers an operator can enter on a TH-D75.
///
/// A missing result is intentional: some MCP fields are editor-only data,
/// operational state, or storage records without a single handheld menu page.
/// Those fields must not be assigned a plausible-looking menu number.
enum THD75MenuNumberIndex {
    static func numbers(for settingID: String) -> [String] {
        if settingID.hasPrefix("radio.GroupLink") { return ["203"] }
        if settingID.hasPrefix("gps.MyPositionList[") { return ["401"] }
        if settingID.hasPrefix("aprs.StatusTextList[") { return ["503"] }
        if settingID.hasPrefix("aprs.ObjectList[") { return ["516"] }
        if settingID.hasPrefix("aprs.UserPhraseList[") { return ["560"] }
        if settingID.hasPrefix("dv.MyDvMessageList[") { return ["611"] }
        if settingID.hasPrefix("dv.MyCallsignDvGatewayList[") { return ["651"] }

        switch settingID {
        // Radio and general configuration
        case "radio.BeatShift": return ["101"]
        case "radio.DetectOutput": return ["102"]
        case "radio.BarAntenna": return ["104"]
        case "radio.WxAlert": return ["105"]
        case "radio.TxInhibit": return ["110"]
        case "radio.TimeOutTimer": return ["111"]
        case "radio.MicSensitivity": return ["112"]
        case "radio.SsbHighCut": return ["120"]
        case "radio.CwWidth": return ["121"]
        case "radio.AmHighCut": return ["122"]
        case "radio.ScanResumeAnalog": return ["130"]
        case "radio.ScanResumeDigital": return ["131"]
        case "radio.TimeRestart": return ["132"]
        case "radio.CarrierRestart": return ["133"]
        case "radio.PriorityScan": return ["134"]
        case "radio.ScanAutoBacklight": return ["135"]
        case "radio.AutoWeatherScan": return ["136"]
        case "radio.AutoOffset": return ["141"]
        case "radio.CallKey": return ["142"]
        case "radio.TxHold1750Hz": return ["143"]
        case "radio.Vox": return ["150"]
        case "radio.VoxGain": return ["151"]
        case "radio.VoxDelay": return ["152"]
        case "radio.VoxTxOnBusy": return ["153"]
        case "radio.DtmfSpeed": return ["160"]
        case "radio.DtmfPauseTime": return ["161"]
        case "radio.DtmfTxHold": return ["162"]
        case "radio.CwPitchFreq": return ["170"]
        case "radio.CwReverse": return ["171"]
        case "radio.QsoLog": return ["180"]
        case "radio.LedControl_Receive", "radio.LedControl_FmRadio": return ["181"]
        case "radio.RecallMethod": return ["202"]
        case "radio.RecordingBand": return ["302"]
        case "radio.TxMonitor": return ["311"]
        case "radio.FmRadioMode": return ["700"]
        case "radio.AutoMuteRetTime": return ["701"]
        case "radio.BacklightControl": return ["900"]
        case "radio.BacklightTimer": return ["901"]
        case "radio.LcdBrightness": return ["902"]
        case "radio.PowerOnMessage": return ["903"]
        case "radio.SingleBandDisplay": return ["904"]
        case "radio.MeterType": return ["905"]
        case "radio.BackgroundColor": return ["906"]
        case "radio.InfoBacklight": return ["907"]
        case "radio.Balance": return ["910"]
        case "radio.TxEqualizerFmNfm", "radio.TxEqualizerDv", "radio.RxEqualizer": return ["911"]
        case "radio.TxEqLevel04", "radio.TxEqLevel08", "radio.TxEqLevel16", "radio.TxEqLevel32": return ["912"]
        case "radio.RxEqLevel04", "radio.RxEqLevel08", "radio.RxEqLevel16", "radio.RxEqLevel32", "radio.RxEqLevel64": return ["913"]
        case "radio.Beep": return ["914"]
        case "radio.BeepVolume": return ["915"]
        case "radio.VoiceAnnounce": return ["916"]
        case "radio.VoiceAnnounceVolume": return ["917"]
        case "radio.VoiceGuidanceSpeed": return ["918"]
        case "radio.CallsignReadout": return ["919"]
        case "radio.UsbAudioOutLevel": return ["91A"]
        case "radio.BatterySaver": return ["920"]
        case "radio.AutoPowerOff": return ["921"]
        case "radio.Charging": return ["923"]
        case "radio.BluetoothOnOff": return ["930"]
        case "radio.BluetoothDeviceName": return ["935"]
        case "radio.BluetoothAutoConnect": return ["936"]
        case "radio.Pf1PfKey": return ["940"]
        case "radio.Pf2PfKey": return ["941"]
        case "radio.Pf1Mic": return ["942"]
        case "radio.Pf2Mic": return ["943"]
        case "radio.Pf3Mic": return ["944"]
        case "radio.CursorShift": return ["945"]
        case "radio.RemoteContorolCode": return ["946"]
        case "radio.TimeZone": return ["950"]
        case "radio.KeyLockTypeKeyLock", "radio.KeyLockTypeFrequencyLock": return ["960"]
        case "radio.DtmfKeys": return ["961"]
        case "radio.MicKeys": return ["962"]
        case "radio.VolumeLockOnOff": return ["963"]
        case "radio.SpeedDistance": return ["970"]
        case "radio.AltitudeRain": return ["971"]
        case "radio.Temperature": return ["972"]
        case "radio.LatitudeLongitude": return ["973"]
        case "radio.GridSquareFormat": return ["974"]
        case "radio.UsbFunction": return ["980"]
        case "radio.PcOutputInterfaceGps": return ["981"]
        case "radio.PcOutputInterfaceAprs": return ["982"]
        case "radio.KissModeInterface": return ["983"]
        case "radio.DigitalModeInterface": return ["984"]
        case "radio.DvGatewayInterface": return ["985"]
        case "radio.Language": return ["990"]

        // GPS
        case "gps.BuiltInGps": return ["400"]
        case "gps.MyPositionSelect": return ["401"]
        case "gps.PositionAmbiguity": return ["402"]
        case "gps.OperatingMode": return ["403"]
        case "gps.BatterySaver": return ["404"]
        case "gps.PcOutput": return ["405"]
        case "gps.Sentence_Gpgga", "gps.Sentence_Gpgll", "gps.Sentence_Gprmc", "gps.Sentence_Gpvtg", "gps.Sentence_Gpgsa", "gps.Sentence_Gpgsv": return ["406"]
        case "gps.TrackLog": return ["410"]
        case "gps.RecodeMethod": return ["412"]
        case "gps.Interval": return ["413"]
        case "gps.Distance": return ["414"]

        // APRS and packet operation
        case "aprs.MyCallsign": return ["500"]
        case "aprs.IconTableOverlay", "aprs.IconSymbol", "aprs.IconNavitra": return ["501"]
        case "aprs.PositionComment": return ["502"]
        case "aprs.StatusTextSelect": return ["503"]
        case "aprs.PacketPathType", "aprs.PacketPathNewNWide11", "aprs.PacketPathNewNHops", "aprs.PacketPathRelayRelay", "aprs.PacketPathRelayHops", "aprs.PacketPathAbbr", "aprs.PacketPathRegionHops", "aprs.PacketPathOthers", "aprs.PacketPathOthers2", "aprs.PacketPathOthers3": return ["504"]
        case "aprs.TncDataSpeed": return ["505"]
        case "aprs.TncDataBand": return ["506"]
        case "aprs.TncDcdSense": return ["507"]
        case "aprs.TncTxDelay": return ["508"]
        case "aprs.Frequency", "aprs.Ptt", "aprs.AprsKey": return ["509"]
        case "aprs.BeaconTxMethod": return ["510"]
        case "aprs.BeaconTxInterval": return ["511"]
        case "aprs.BeaconTxDecay": return ["512"]
        case "aprs.BeaconTxProportion": return ["513"]
        case "aprs.BeaconSpeedOff": return ["514"]
        case "aprs.BeaconAltitudeOff": return ["515"]
        case "aprs.ObjectUsedNo": return ["516"]
        case "aprs.QsyInStatus": return ["520"]
        case "aprs.QsyToneNarrow": return ["521"]
        case "aprs.QsyShiftOffset": return ["522"]
        case "aprs.QsyLimit": return ["523"]
        case "aprs.LowSpeedSpeed", "aprs.HiSpeedSpeed": return ["530"]
        case "aprs.SlowRateTime": return ["531"]
        case "aprs.FastRateTime": return ["532"]
        case "aprs.TurnAngleDeg": return ["533"]
        case "aprs.TurnSlopeDegSpeed": return ["534"]
        case "aprs.TurnTimeTime": return ["535"]
        case "aprs.WaypointFormat": return ["540"]
        case "aprs.WaypointLength": return ["541"]
        case "aprs.WaypointOutput": return ["542"]
        case "aprs.FilterPositionLimit": return ["550"]
        case "aprs.FilterType_Weather", "aprs.FilterType_Digipeater", "aprs.FilterType_Mobile", "aprs.FilterType_Object", "aprs.FilterType_Navitra", "aprs.FilterType_1Way", "aprs.FilterType_Others": return ["551"]
        case "aprs.AutoReplyOnOff": return ["561"]
        case "aprs.AutoReplyTargetCall": return ["562"]
        case "aprs.AutoReplyDelayTime": return ["563"]
        case "aprs.AutoReplyMessage": return ["564"]
        case "aprs.RxBeepType": return ["570"]
        case "aprs.TxBeepOnOff": return ["571"]
        case "aprs.SpecialCall": return ["572"]
        case "aprs.InterruptDisplayArea": return ["573"]
        case "aprs.InterruptDisplayTime": return ["574"]
        case "aprs.AprsVoice": return ["575"]
        case "aprs.DigipeatMyCallsign": return ["580"]
        case "aprs.UIcheck": return ["581"]
        case "aprs.UIdigipeat": return ["582"]
        case "aprs.UIdigiAliases": return ["583"]
        case "aprs.UIflood": return ["584"]
        case "aprs.UIfloodAliases": return ["585"]
        case "aprs.UIfloodSubstitution": return ["586"]
        case "aprs.UItrace": return ["587"]
        case "aprs.UItraceAliases": return ["588"]
        case "aprs.PcOutput": return ["590"]
        case "aprs.NetworkType", "aprs.AltnetAddress": return ["591"]
        case "aprs.VoiceAlertOnOff": return ["592"]
        case "aprs.VoiceAlertToneNo": return ["593"]
        case "aprs.MessageGroup": return ["594"]
        case "aprs.BulletinGroup": return ["595"]

        // D-STAR and DV Gateway
        case "dv.AutoReply": return ["312"]
        case "dv.DirectReplyTxRx": return ["612"]
        case "dv.AutoReplyTimingTxRx": return ["613"]
        case "dv.DataTxEndTimingTxRx": return ["614"]
        case "dv.EmrVolumeLevelTxRx": return ["615"]
        case "dv.RxAfcTxRx": return ["616"]
        case "dv.FmAutoDetOnDvTxRx": return ["617"]
        case "dv.DataFrameOutputTxRx": return ["618"]
        case "dv.GpsInfoInFrameGpsDataTx": return ["630"]
        case "dv.SentenceGpsDataTx_Gpgga", "dv.SentenceGpsDataTx_Gpgll", "dv.SentenceGpsDataTx_Gprmc", "dv.SentenceGpsDataTx_Gpvtg", "dv.SentenceGpsDataTx_Gpgsa", "dv.SentenceGpsDataTx_Gpgsv", "dv.SentenceGpsDataTx_Aprs": return ["631"]
        case "dv.AutoTxGpsDataTx": return ["632"]
        case "dv.DisplayMethodRxNotification": return ["640"]
        case "dv.SingleDisplaySizeRxNotification": return ["641"]
        case "dv.DualDisplaySizeRxNotification": return ["642"]
        case "dv.DisplayHoldTimeRxNotification": return ["643"]
        case "dv.CallsignAnnounceRxNotification": return ["644"]
        case "dv.StandbyBeepRxNotification": return ["645"]
        case "dv.DvGatewayModeDvGateway": return ["650"]
        case "dv.MyCallsignSelectDvGateway": return ["651"]
        case "dv.RPT1DvGateway": return ["652"]
        case "dv.RPT2DvGateway": return ["653"]
        case "dv.DeviceNameDvGateway": return ["654"]
        case "dv.MyDvMessageSelect": return ["611"]

        default: return []
        }
    }
}
